<?php

if (!function_exists("generateUsername")) {
    /**
     * Generate a username from a full name.
     *
     * The username will be generated by first converting the full name to
     * lowercase, then removing any whitespace and non-alphanumeric characters.
     *
     * @param string|array $fullName The full name to generate a username from
     *
     * @return string The generated username
     */
    function generateUsername($fullName)
    {
        if (is_array($fullName)) {
            $fullName = implode(" ", $fullName);
        }

        $fullName = strtolower(preg_replace('/\s+/', '', $fullName));
        $fullName = preg_replace('/[^a-zA-Z0-9]/', '', $fullName);

        return $fullName;
    }
}

if (!function_exists('generateSocialMediaUrls')) {
    /**
     * Generate an array of social media URLs from a full name.
     *
     * The returned array will contain the following keys: 'facebook', 'twitter',
     * 'instagram', 'linkedin', 'youtube', and 'tiktok'. The values will be a URL
     * for each social media platform, with the username generated by
     * {@see generateUsername()} followed by a random 2-digit number.
     *
     * @param string $fullName The full name to generate social media URLs from
     *
     * @return array An array of social media URLs with the keys listed above
     */
    function generateSocialMediaUrls(string $fullName): array
    {
        $username = generateUsername($fullName) . rand(10, 99);

        return [
            'facebook' => "https://facebook.com/{$username}",
            'twitter' => "https://twitter.com/{$username}",
            'instagram' => "https://instagram.com/{$username}",
            'linkedin' => "https://linkedin.com/in/{$username}",
            'youtube' => "https://youtube.com/{$username}",
            'tiktok' => "https://tiktok.com/@{$username}",
        ];
    }
}
